# Generated by Django 4.2.5 on 2023-09-26 15:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FullProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processID', models.PositiveIntegerField()),
                ('initTrainingDataNum', models.PositiveIntegerField()),
                ('initTrainingDataSelectMethod', models.CharField(max_length=200)),
                ('trainingModel', models.CharField(max_length=200)),
                ('uncertaintyQueryMethod', models.CharField(max_length=200)),
                ('querySize', models.PositiveIntegerField()),
                ('poolingSize', models.PositiveIntegerField()),
                ('learningRate', models.FloatField()),
                ('numEpochs', models.PositiveIntegerField()),
                ('batchSize', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('df', picklefield.fields.PickledObjectField(default='default dataframe', editable=False)),
                ('processID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset', to='api.fullprocess')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nthIter', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None)),
                ('cumulatedNumData', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('trainAcc', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None)),
                ('testAcc', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None)),
                ('processID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activelearning', to='api.fullprocess')),
            ],
        ),
    ]
