# Generated by Django 4.2.5 on 2023-09-14 06:44

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('df', picklefield.fields.PickledObjectField(default='default dataframe', editable=False)),
            ],
        ),
    ]
