# Generated by Django 4.2.5 on 2023-09-19 04:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('initTrainingDataNum', models.IntegerField()),
                ('initTrainingDataSelectMethod', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('uncertaintyQueryMethod', models.CharField(max_length=200)),
                ('querySize', models.IntegerField()),
                ('poolingSize', models.IntegerField()),
                ('learningRate', models.FloatField()),
                ('numEpochs', models.IntegerField()),
                ('batchSize', models.IntegerField()),
                ('nthIter', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('cumulatedNumData', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('trainAcc', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('testAcc', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
        ),
    ]
