# Generated by Django 4.2.5 on 2023-10-01 17:33

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dataset_labelornot_dataset_predictionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelearning',
            name='cumulatedNumData',
            field=django_jsonform.models.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='activelearning',
            name='nthIter',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='activelearning',
            name='queryIdxByIter',
            field=django_jsonform.models.fields.ArrayField(base_field=django_jsonform.models.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='activelearning',
            name='testAcc',
            field=django_jsonform.models.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='activelearning',
            name='trainAcc',
            field=django_jsonform.models.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='labelOrNot',
            field=django_jsonform.models.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='predictionRecord',
            field=django_jsonform.models.fields.ArrayField(base_field=django_jsonform.models.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None), default=list, size=None),
        ),
    ]
