# Generated by Django 4.2.5 on 2023-11-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dataset_data_dataset_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullprocess',
            name='finalStudentAcc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fullprocess',
            name='finalTeacherAcc',
            field=models.FloatField(default=0),
        ),
    ]
