# Generated by Django 4.2.5 on 2023-11-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_fullprocess_imputermethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullprocess',
            name='yLabel',
            field=models.CharField(default='ylabel', max_length=200),
        ),
    ]
